const env = process.env as Record<string, string | undefined>;

const DEFAULT_API_BASE_URL = 'http://192.168.0.52:8000';

export const API_BASE_URL = env.EXPO_PUBLIC_API_BASE_URL ?? DEFAULT_API_BASE_URL;
export const WS_BASE_URL = env.EXPO_PUBLIC_WS_BASE_URL ?? API_BASE_URL.replace(/^http/, 'ws');

export const GOOGLE_CLIENT_ID = env.EXPO_PUBLIC_GOOGLE_CLIENT_ID ?? env.GOOGLE_CLIENT_ID ?? '';
export const GOOGLE_ANDROID_CLIENT_ID = env.EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID ?? GOOGLE_CLIENT_ID;
export const GOOGLE_IOS_CLIENT_ID = env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID ?? GOOGLE_CLIENT_ID;
export const GOOGLE_WEB_CLIENT_ID = env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID ?? GOOGLE_CLIENT_ID;
