import { StyleSheet } from 'react-native';
import { Colors } from './theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.bg },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: Colors.white,
    borderBottomWidth: 0.5,
    borderBottomColor: Colors.border,
  },
  logo: { fontSize: 20, fontWeight: '700', color: Colors.mint },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  logoutBtn: {
    height: 32,
    borderRadius: 16,
    paddingHorizontal: 10,
    backgroundColor: '#FAECE7',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  logoutText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#D85A30',
  },
  avatarBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.mintLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scroll: {
    paddingHorizontal: 24,
    paddingTop: 18,
    paddingBottom: 32,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#888',
    letterSpacing: 0.3,
  },
  grid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  gridItem: {
    width: '23%',
    backgroundColor: Colors.white,
    borderRadius: 14,
    borderWidth: 0.5,
    borderColor: Colors.borderLight,
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 4,
  },
  gridIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: Colors.mintLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  gridLabel: { fontSize: 11, color: Colors.textMid, fontWeight: '500', textAlign: 'center' },
  emptyBox: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    borderWidth: 0.5,
    borderColor: Colors.borderLight,
    paddingVertical: 32,
    alignItems: 'center',
    gap: 8,
  },
  emptyGif: {
    width: 160,
    height: 120,
  },
  emptyTitle: {
    fontSize: 13,
    fontWeight: '500',
    color: Colors.textDark,
    textAlign: 'center',
  },
  emptyText: { fontSize: 12, color: Colors.textLight, textAlign: 'center', lineHeight: 18 },
  workItem: {
    backgroundColor: Colors.white,
    borderRadius: 14,
    borderWidth: 0.5,
    borderColor: Colors.borderLight,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 8,
  },
  workIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: Colors.mintLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  workType: { fontSize: 11, color: Colors.mint, fontWeight: '600' },
  workTitle: { fontSize: 13, color: Colors.textDark, fontWeight: '500', marginTop: 2 },

  recentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    marginTop: 8,
  },
  recentHeaderMore: {
    fontSize: 12,
    color: Colors.mint,
    fontWeight: '500',
  },
  mainCard: {
    backgroundColor: Colors.white,
    borderRadius: 12,
    borderWidth: 0.5,
    borderColor: Colors.borderLight,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  mainCardIcon: {
    width: 44,
    height: 44,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mainCardBody: {
    flex: 1,
    minWidth: 0,
  },
  mainCardTitle: {
    fontSize: 14,
    fontWeight: '500',
    color: Colors.textDark,
    marginBottom: 2,
  },
  mainCardDate: {
    fontSize: 11,
    color: Colors.textLight,
    marginBottom: 8,
  },
  mainCardBadgeRow: {
    flexDirection: 'row',
    gap: 5,
    flexWrap: 'wrap',
  },
  mainCardProgress: {
    height: 3,
    backgroundColor: Colors.border,
    borderRadius: 2,
    marginTop: 8,
  },
  mainCardSummary: {
    marginTop: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: Colors.bg,
    borderLeftWidth: 2,
    borderLeftColor: '#5DCAA5',
  },
  mainCardSummaryText: {
    fontSize: 11,
    color: Colors.textLight,
    lineHeight: 16,
  },
  mainCardChevron: {
    alignSelf: 'center',
  },
  subCardRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  subCard: {
    flex: 1,
    backgroundColor: Colors.white,
    borderRadius: 8,
    borderWidth: 0.5,
    borderColor: Colors.borderLight,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  subCardIcon: {
    width: 28,
    height: 28,
    borderRadius: 6,
    backgroundColor: Colors.mintLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  subCardBody: {
    flex: 1,
    minWidth: 0,
  },
  subCardTitle: {
    fontSize: 11,
    fontWeight: '500',
    color: Colors.textDark,
  },
  subCardBadge: {
    marginTop: 3,
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '500',
  },
  recentList: {
    gap: 8,
  },
  retryButton: {
    marginTop: 12,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: Colors.mintLight,
  },
  retryText: {
    fontSize: 12,
    color: Colors.mint,
    fontWeight: '600',
  },
});
