import { StyleSheet } from 'react-native';
import { Colors } from './theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.white },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 0.5,
    borderBottomColor: Colors.border,
  },
  cancelBtn: { fontSize: 15, color: Colors.textMid },
  langBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#f5f5f5',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  langText: { fontSize: 13, color: Colors.textMid },
  timerSection: { alignItems: 'center', paddingTop: 32, paddingBottom: 12 },
  timerRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
  recDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.mint,
  },
  recDotPaused: { backgroundColor: '#ccc' },
  timer: { fontSize: 28, fontWeight: '300', color: Colors.textDark, letterSpacing: 2 },
  recordTitle: { fontSize: 18, fontWeight: '600', color: Colors.textDark },
  waveContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    paddingHorizontal: 20,
    marginVertical: 20,
    height: 40,
  },
  waveBar: {
    width: 3,
    height: 12,
    borderRadius: 2,
    backgroundColor: '#e0e0e0',
  },
  waveBarActive: { backgroundColor: Colors.mint, height: 28 },
  highlightBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'center',
    marginBottom: 16,
  },
  highlightText: { fontSize: 14, color: Colors.mint, fontWeight: '500' },
  scriptContainer: {
    flex: 1,
    marginHorizontal: 20,
    backgroundColor: Colors.bg,
    borderRadius: 16,
    borderWidth: 0.5,
    borderColor: '#e0f0eb',
    padding: 14,
    marginBottom: 12,
  },
  scriptHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 10,
  },
  scriptHeaderText: { fontSize: 12, color: Colors.mint, fontWeight: '600' },
  scriptScroll: { flex: 1 },
  scriptItem: { marginBottom: 10 },
  scriptTime: { fontSize: 11, color: Colors.textLight, marginBottom: 2 },
  scriptText: { fontSize: 14, color: '#333', lineHeight: 20 },
  scriptTyping: { color: '#bbb', fontStyle: 'italic' },
  notice: {
    fontSize: 12,
    color: '#bbb',
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: 12,
  },
  controls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 32,
    marginBottom: 20,
  },
  controlSide: {
    width: 56,
    alignItems: 'center',
    justifyContent: 'center',
  },
  centerCol: {
    alignItems: 'center',
    gap: 6,
  },
  cancelText: { fontSize: 14, color: '#888' },
  saveLabel: { fontSize: 11, color: Colors.textLight },
  mainBtn: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#f0f0f0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  mainBtnPaused: { backgroundColor: Colors.mint },
  stopBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.textDark,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stopIcon: {
    width: 16,
    height: 16,
    borderRadius: 2,
    backgroundColor: Colors.white,
  },
  pauseLabel: { fontSize: 11, color: Colors.textLight },
});
